version: '3'
services:
  server:
    image: vid-info-svr
    volumes:
      - /var/vms/Jon/Documents/GitHub/vidInfo:/usr/src/app
      - node_modules:/usr/src/app/node_modules/
    ports:
      - "8000:8000"
      - "8080:8080"
      - "5858:5858"
  app:
    build: .
    command: /bin/bash
    links:
      - server
volumes:
  node_modules:
