version: '2'
services:
  web:
    build: .
    depends_on:
    - cp-pg-server
    - pg-client
    command: bash
    stdin_open: true
    tty: true
    ports:
    - "8000:8000"
    links:
    - cp-pg-server
    volumes:
    - /var/vmshare/Jon/Documents/GitHub/backend2:/usr/src/app
  cp-pg-server:
    image: cp-pg-svr
    ports:
    - "5432:5432"
  pg-client:
    image: postgres:9.5.4
    command: bash
    stdin_open: true
    tty: true
